name=SBUS decoder
version=1.0.1
author=<https://github.com/MercyPpctsk>
maintainer=Ralph McCleery <macca448@gmail.com
sentence=A lightweight SBUS 10 channel decoder library
paragraph=This library parses 10-channel SBUS data and maps raw endpoints (309-1690) to standard PWM (1000-2000us) seamlessly. Should support any Arduino using HarwareSerial
category=Signal Input/Output
url=https://github.com/macca448/SBUS
architectures=*
